"""Casa de la bolsa. Quien caza aquí no ensucia el manto de las monedas.

El rey es el índice grande. La reina es la rápida. Corea de tres
y la plata se quedan con las monedas. El metal del escudo no caza.
"""
from __future__ import annotations

REINA = "US100-USDT-SWAP"
REY = "US500-USDT-SWAP"
MAREA = (
    "SOXL-USDT-SWAP",
    "NVDA-USDT-SWAP",
    "AAPL-USDT-SWAP",
    "AMZN-USDT-SWAP",
    "MSFT-USDT-SWAP",
    "TSLA-USDT-SWAP",
    "AVGO-USDT-SWAP",
    "COIN-USDT-SWAP",
)

# Nombre, sala. La sala es la más estrecha donde el lote todavía abre.
SALAS: dict[str, str] = {
    "AAOI": "rojo",
    "AAPL": "verde",
    "ADBE": "amarillo",
    "ALAB": "verde",
    "AMZN": "amarillo",
    "ANTHROPIC": "rojo",
    "APLD": "amarillo",
    "APP": "amarillo",
    "ARM": "amarillo",
    "ASML": "rojo",
    "ASTS": "rojo",
    "AVGO": "verde",
    "AXTI": "rojo",
    "BE": "amarillo",
    "BMNR": "amarillo",
    "BOT": "amarillo",
    "BRKB": "verde",
    "BSP": "verde",
    "BX": "rojo",
    "CBRS": "rojo",
    "CIEN": "verde",
    "COHR": "amarillo",
    "COIN": "rojo",
    "COST": "rojo",
    "CRDO": "rojo",
    "CRM": "amarillo",
    "CRWD": "amarillo",
    "CRWV": "rojo",
    "CSCO": "rojo",
    "DDOG": "amarillo",
    "DKNG": "rojo",
    "EWJ": "rojo",
    "EWT": "rojo",
    "EWY": "rojo",
    "EWZ": "verde",
    "FLNC": "rojo",
    "FLY": "amarillo",
    "GEV": "rojo",
    "GLW": "rojo",
    "GME": "amarillo",
    "GOOGL": "verde",
    "GTLB": "verde",
    "HANMI": "rojo",
    "HIMS": "amarillo",
    "HUT": "rojo",
    "HYUNDAI": "amarillo",
    "IBM": "amarillo",
    "INFQ": "rojo",
    "INTW": "amarillo",
    "IONQ": "verde",
    "IREN": "verde",
    "ISRG": "verde",
    "IWM": "amarillo",
    "JNJ": "amarillo",
    "KIOXIA": "rojo",
    "KLAC": "rojo",
    "KR200": "rojo",
    "KSTR": "amarillo",
    "LGELECTRONICS": "rojo",
    "LRCX": "verde",
    "LUNR": "rojo",
    "LYTE": "amarillo",
    "MARA": "rojo",
    "MINIMAX": "amarillo",
    "MRK": "rojo",
    "MRNA": "rojo",
    "MRVL": "amarillo",
    "MSFT": "verde",
    "MSTR": "rojo",
    "MSTU": "verde",
    "MUU": "rojo",
    "MVLL": "verde",
    "NAVER": "rojo",
    "NBIS": "amarillo",
    "NET": "verde",
    "NFLX": "rojo",
    "NOK": "rojo",
    "NOW": "rojo",
    "NVDA": "amarillo",
    "NVDL": "verde",
    "OKLO": "verde",
    "OKTA": "rojo",
    "OPENAI": "rojo",
    "ORCL": "rojo",
    "OSCR": "amarillo",
    "OURA": "verde",
    "OUST": "verde",
    "PLTR": "rojo",
    "POET": "rojo",
    "POPMART": "rojo",
    "PURR": "rojo",
    "QCOM": "rojo",
    "QNT": "verde",
    "RAM": "rojo",
    "RDDT": "rojo",
    "RDW": "rojo",
    "RIOT": "rojo",
    "RIVN": "rojo",
    "RKLB": "rojo",
    "ROK": "verde",
    "SAMSUNG": "rojo",
    "SHAZ": "verde",
    "SHOP": "rojo",
    "SIMO": "amarillo",
    "SKDD": "rojo",
    "SKHY": "rojo",
    "SKHYNIX": "rojo",
    "SKUU": "amarillo",
    "SMCI": "verde",
    "SNDK": "rojo",
    "SNOW": "verde",
    "SNXX": "rojo",
    "SOFTBANK": "verde",
    "SONY": "amarillo",
    "SOXL": "rojo",
    "SOXS": "amarillo",
    "SPCX": "rojo",
    "TEAM": "rojo",
    "TER": "verde",
    "TMF": "amarillo",
    "TSEM": "amarillo",
    "TSLA": "verde",
    "TSM": "verde",
    "TTMI": "rojo",
    "TTWO": "rojo",
    "TWLO": "amarillo",
    "UNH": "verde",
    "UNITREE": "rojo",
    "URNM": "verde",
    "USAR": "rojo",
    "USO": "rojo",
    "UVXY": "rojo",
    "VRT": "amarillo",
    "WDC": "verde",
    "WMT": "rojo",
    "XBI": "rojo",
    "XOM": "rojo",
    "ZHIPU": "rojo",
    "ZHONGJI": "rojo",
}


def cazadores() -> set[str]:
    return set(SALAS)


def es_cazador(activo: str) -> bool:
    return str(activo or "").strip().upper() in SALAS


def sala(activo: str) -> str | None:
    return SALAS.get(str(activo or "").strip().upper())
